-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TEXT COLORS

local text-primary = "rgb(dcdcdc)"

local text-primary-alpha = "dcdcdc"

local text-secondary = "rgb(b4b4b4)"

local text-secondary-alpha = "b4b4b4"

local text-tertiary = "rgb(969696)"

local text-tertiary-alpha = 969696

-- BACKGROUND COLORS (dark to light)

local bg-deepest = "rgb(141414)"

local bg-deepest-alpha = 141414

local bg-darker = "rgb(191919)"

local bg-darker-alpha = 191919

local bg-dark = "rgb(1e1e1e)"

local bg-dark-alpha = "1e1e1e"

-- SURFACE COLORS (for UI elements)

local surface-dark = "rgb(282828)"

local surface-dark-alpha = 282828

local surface-medium = "rgb(323232)"

local surface-medium-alpha = 323232

local surface-light = "rgb(464646)"

local surface-light-alpha = 464646

-- OVERLAY COLORS (for disabled/disabled states)

local overlay-dark = "rgb(5a5a5a)"

local overlay-dark-alpha = "5a5a5a"

local overlay-medium = "rgb(6e6e6e)"

local overlay-medium-alpha = "6e6e6e"

local overlay-light = "rgb(828282)"

local overlay-light-alpha = 828282

-- ACCENT COLORS (main theme color)

local accent-primary = "rgb(3b82f6)"

-- Deep Blue

local accent-primary-alpha = "3b82f6"

-- SEMANTIC COLORS (for specific meanings)

local semantic-error = "rgb(ef4444)"

-- Яркий красный

local semantic-error-alpha = "ef4444"

local semantic-warning = "rgb(fbbf24)"

-- Яркий жёлтый

local semantic-warning-alpha = "fbbf24"

local semantic-success = "rgb(7bc379)"

-- Яркий зелёный

local semantic-success-alpha = "7bc379"

local semantic-info = "rgb(0ea5e9)"

-- Яркий голубой

local semantic-info-alpha = "0ea5e9"

-- UTILITY COLORS (miscellaneous)

local utility-blue = "rgb(3b82f6)"

local utility-blue-alpha = "3b82f6"

local utility-cyan = "rgb(06b6d4)"

local utility-cyan-alpha = "06b6d4"

local utility-green = "rgb(7bc379)"

local utility-green-alpha = "7bc379"

local utility-yellow = "rgb(eab308)"

local utility-yellow-alpha = "eab308"

local utility-orange = "rgb(f97316)"

local utility-orange-alpha = "f97316"

local utility-red = "rgb(ef4444)"

local utility-red-alpha = "ef4444"

local utility-purple = "rgb(8b5cf6)"

local utility-purple-alpha = "8b5cf6"
