-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- source = $HOME/.config/hypr/hyprlockThemes/dark/monochrome.conf -> requires manual conversion
-- local monochrome = require("hyprlockThemes.dark.monochrome")
-- TODO: convert $HOME/.config/hypr/hyprlockThemes/dark/monochrome.conf to .lua and use require()

local accent = "local_var_accent-primary"

local accentAlpha = "local_var_accent-primary-primary-alpha"

local font = "JetBrainsMono Nerd Font"

-- GENERAL

hl.config({
    general = {
        disable_loading_bar = true,
        hide_cursor = true,
    },
})

-- BACKGROUND

hl.config({
    background = {
        path = os.getenv("HOME") .. "/.config/background",
        blur_passes = 0,
        color = bg-dark,
    },
})
-- NOTE: Section 'background' may be a plugin or custom section; verify the output

-- LAYOUT

hl.config({
    label = {
        text = " local_var_LAYOUT",
        color = text-primary,
        font_size = 20,
        font_family = "JetBrainsMono Nerd Font",
        position = { 30, -30 },
        halign = "left",
        valign = "top",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- TIME

hl.config({
    label = {
        text = TIME,
        color = text-primary,
        font_size = 90,
        font_family = "JetBrainsMono Nerd Font",
        position = { -30, 0 },
        halign = "right",
        valign = "top",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- DATE

hl.config({
    label = {
        text = "cmd[update:43200000] date+ %A, %d %B %Y",
        color = text-primary,
        font_size = 25,
        font_family = "JetBrainsMono Nerd Font",
        position = { -30, -150 },
        halign = "right",
        valign = "top",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- FINGERPRINT (Square style)

hl.config({
    label = {
        text = FPRINTPROMPT,
        color = text-primary,
        font_size = 14,
        font_family = "JetBrainsMono Nerd Font",
        position = { 0, -107 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- USER AVATAR (Square style)

--image {

--  monitor =

--  path = /home/abeb-arch/.config/hypr/assets/face.png

--  size = 150

--   border_color = $accent

--   border_size = 4

--   rounding = 0  # Square avatar

--   position = 0, 75

--   halign = center

--   valign = center

-- }

-- INPUT FIELD (Square style)

hl.config({
    input-field = {
        size = { 300, 60 },
        rounding = 1,
        -- Square corners
        outline_thickness = 3,
        dots_size = 0.2,
        dots_spacing = 0.2,
        dots_center = true,
        outer_color = accent-primary,
        inner_color = surface-dark,
        font_color = text-primary,
        fade_on_empty = false,
        placeholder_text = "<span foreground=##local_var_text-primary-alpha > Logged in as <span foreground=##local_var_accent-primary-primary-alpha >" .. os.getenv("USER") .. "</span></span>",
        hide_input = false,
        check_color = accent-primary,
        fail_color = semantic-error,
        fail_text = "<i>local_var_FAIL <b>(local_var_ATTEMPTS)</b></i>",
        capslock_color = semantic-warning,
        position = { 0, -47 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'input-field' may be a plugin or custom section; verify the output

-- Additional square elements for visual consistency

-- Square border around fingerprint area

hl.config({
    image = {
        color = accent-primary,
        size = { 320, 80 },
        rounding = 0,
        border_size = 2,
        border_color = accent-primary,
        position = { 0, -107 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'image' may be a plugin or custom section; verify the output

-- Square border around input field

hl.config({
    image = {
        color = surface-dark,
        size = { 304, 64 },
        rounding = 0,
        border_size = 0,
        position = { 0, -47 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'image' may be a plugin or custom section; verify the output
