-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        lock_cmd = "hyprlock",
        -- use hyprlock for screen locking
        before_sleep_cmd = "loginctl lock-session",
        -- lock before system suspend
        after_sleep_cmd = "hyprctl dispatch dpms on",
        -- wake display after suspend so you don’t need an extra key press
    },
})

-- --- Step 1: Dim screen + turn off keyboard backlight ---

hl.config({
    listener = {
        timeout = 120,
        -- after 2 minutes of inactivity
        on_timeout = "brightnessctl -s set 30%",
        -- dim screen (don’t go fully dark to avoid OLED burn-in)
        on_resume = "brightnessctl -r",
        -- restore brightness on activity
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 120,
        -- same 2 minutes of inactivity
        on_timeout = "brightnessctl -sd rgb:kbd_backlight set 0",
        -- turn off keyboard backlight (if available)
        on_resume = "brightnessctl -rd rgb:kbd_backlight",
        -- restore keyboard backlight
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

-- --- Step 2: Lock session ---

hl.config({
    listener = {
        timeout = 300,
        -- after 5 minutes of inactivity
        on_timeout = "loginctl lock-session",
        -- lock the screen
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

-- --- Step 3: Turn off display ---

hl.config({
    listener = {
        timeout = 600,
        -- after 10 minutes of inactivity
        on_timeout = "hyprctl dispatch dpms off",
        -- turn off display (DPMS)
        on_resume = "hyprctl dispatch dpms on && brightnessctl -r",
        -- turn display back on and restore brightness
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

-- --- Step 4: Suspend system ---

hl.config({
    listener = {
        timeout = 900,
        -- after 15 minutes of inactivity
        on_timeout = "systemctl suspend",
        -- suspend the laptop
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

-- --- Step 5: Hibernate system ---

hl.config({
    listener = {
        timeout = 1800,
        -- after 30 minutes of inactivity
        on_timeout = "systemctl hibernate",
        -- hibernate the laptop (sleep from disk)
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output
