-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TEXT COLORS

local text-primary = "rgb(dcdcdc)"

local text-primary-alpha = "dcdcdc"

local text-secondary = "rgb(b4b4b4)"

local text-secondary-alpha = "b4b4b4"

local text-tertiary = "rgb(969696)"

local text-tertiary-alpha = 969696

-- BACKGROUND COLORS (dark to light)

local bg-deepest = "rgb(141414)"

local bg-deepest-alpha = 141414

local bg-darker = "rgb(191919)"

local bg-darker-alpha = 191919

local bg-dark = "rgb(1e1e1e)"

local bg-dark-alpha = "1e1e1e"

-- SURFACE COLORS (for UI elements)

local surface-dark = "rgb(282828)"

local surface-dark-alpha = 282828

local surface-medium = "rgb(323232)"

local surface-medium-alpha = 323232

local surface-light = "rgb(464646)"

local surface-light-alpha = 464646

-- OVERLAY COLORS (for disabled/disabled states)

local overlay-dark = "rgb(5a5a5a)"

local overlay-dark-alpha = "5a5a5a"

local overlay-medium = "rgb(6e6e6e)"

local overlay-medium-alpha = "6e6e6e"

local overlay-light = "rgb(828282)"

local overlay-light-alpha = 828282

-- ACCENT COLORS (main theme color)

local accent-primary = "rgb(e0e0e0)"

local accent-primary-alpha = "e0e0e0"

-- SEMANTIC COLORS (consistent red / yellow / green)

local semantic-error = "rgb(ef4444)"

local semantic-error-alpha = "ef4444"

local semantic-warning = "rgb(eab308)"

local semantic-warning-alpha = "eab308"

local semantic-success = "rgb(7bc379)"

local semantic-success-alpha = "7bc379"

local semantic-info = "rgb(909090)"

local semantic-info-alpha = 909090

-- UTILITY COLORS (grayscale only)

local utility-blue = "rgb(e0e0e0)"

local utility-blue-alpha = "e0e0e0"

local utility-cyan = "rgb(c8c8c8)"

local utility-cyan-alpha = "c8c8c8"

local utility-green = "rgb(b8b8b8)"

local utility-green-alpha = "b8b8b8"

local utility-yellow = "rgb(a8a8a8)"

local utility-yellow-alpha = "a8a8a8"

local utility-orange = "rgb(989898)"

local utility-orange-alpha = 989898

local utility-red = "rgb(f0f0f0)"

local utility-red-alpha = "f0f0f0"

local utility-purple = "rgb(d0d0d0)"

local utility-purple-alpha = "d0d0d0"
