-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TEXT COLORS

local text-primary = "rgb(dcdcdc)"

local text-primary-alpha = "dcdcdc"

local text-secondary = "rgb(b4b4b4)"

local text-secondary-alpha = "b4b4b4"

local text-tertiary = "rgb(969696)"

local text-tertiary-alpha = 969696

-- BACKGROUND COLORS (dark to light)

local bg-deepest = "rgb(141414)"

-- Самый тёмный фон

local bg-deepest-alpha = 141414

local bg-darker = "rgb(191919)"

-- Темнее

local bg-darker-alpha = 191919

local bg-dark = "rgb(1e1e1e)"

-- Тёмный фон

local bg-dark-alpha = "1e1e1e"

-- SURFACE COLORS (for UI elements)

local surface-dark = "rgb(282828)"

-- Тёмная поверхность

local surface-dark-alpha = 282828

local surface-medium = "rgb(323232)"

-- Средняя поверхность

local surface-medium-alpha = 323232

local surface-light = "rgb(464646)"

-- Светлая поверхность

local surface-light-alpha = 464646

-- OVERLAY COLORS (for disabled/disabled states)

local overlay-dark = "rgb(5a5a5a)"

-- Тёмный оверлей

local overlay-dark-alpha = "5a5a5a"

local overlay-medium = "rgb(6e6e6e)"

-- Средний оверлей

local overlay-medium-alpha = "6e6e6e"

local overlay-light = "rgb(828282)"

-- Светлый оверлей

local overlay-light-alpha = 828282

-- ACCENT COLORS (main theme color)

local accent-primary = "rgb(9869db)"

-- Основной акцент

local accent-primary-alpha = "9869db"

-- SEMANTIC COLORS (for specific meanings)

local semantic-error = "rgb(e06c75)"

-- Ошибки

local semantic-error-alpha = "e06c75"

local semantic-warning = "rgb(e5c07b)"

-- Предупреждения

local semantic-warning-alpha = "e5c07b"

local semantic-success = "rgb(98c379)"

-- Успех

local semantic-success-alpha = "98c379"

local semantic-info = "rgb(61afef)"

-- Информация

local semantic-info-alpha = "61afef"

-- UTILITY COLORS (miscellaneous)

local utility-blue = "rgb(61afef)"

-- Синий

local utility-blue-alpha = "61afef"

local utility-cyan = "rgb(56b6c2)"

-- Голубой

local utility-cyan-alpha = "56b6c2"

local utility-green = "rgb(98c379)"

-- Зелёный

local utility-green-alpha = "98c379"

local utility-yellow = "rgb(e5c07b)"

-- Жёлтый

local utility-yellow-alpha = "e5c07b"

local utility-orange = "rgb(d19a66)"

-- Оранжевый

local utility-orange-alpha = "d19a66"

local utility-red = "rgb(e06c75)"

-- Красный

local utility-red-alpha = "e06c75"

local utility-purple = "rgb(c678dd)"

-- Пурпурный

local utility-purple-alpha = "c678dd"
