---@module 'hl'

-- Generated by nwg-displays on 2025-07-24 at 16:08:54. Do not edit manually.

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1200@60",
    position = "0x0",
    scale    = 1.2,
})

-- External monitor (uncomment if needed):
-- hl.monitor({
--     output   = "DP-1",
--     mode     = "1920x1080@144",
--     position = "0x0",
--     scale    = 1.0,
-- })
