# MONOCHROME THEME FOR KITTY
foreground #d4d4d4
background #000000

# Black
color0 #151521
color8 #39394a

# Red
color1 #ff6b6b
color9 #ff8f8f

# Green
color2 #a0a0a0
color10 #c8c8c8

# Yellow
color3 #909090
color11 #b8b8b8

# Blue
color4 #e0e0e0
color12 #f0f0f0

# Magenta
color5 #888888
color13 #a8a8a8

# Cyan
color6 #787878
color14 #989898

# White
color7 #d4d4d4
color15 #ffffff

# Cursor
cursor #e0e0e0
cursor_text_color #000000

# Selection
selection_foreground #000000
selection_background #e0e0e0
