-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'


--exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark" # Установка темной темы




-- Stores text only


-- Stores images (screenshots)


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper --config ~/.config/hypr/hyprpaper.conf & waybar & swaync & hypridle & hyprsunset")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme \"Dracula\"")
    hl.exec_cmd("gsettings set org.gnome.desktop.wm.preferences theme \"Dracula\"")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
end)
