-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    decoration = {
        rounding = 1,
        blur = {
            enabled = true,
            size = 10,
            passes = 3,
            new_optimizations = true,
            ignore_opacity = true,
        },
        active_opacity = 1,
        inactive_opacity = 0.88,
    },
})
