-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    dwindle = {
        force_split = 0,
        smart_split = false,
        smart_resizing = true,
        split_width_multiplier = 1.0,
        use_active_for_splits = true,
        default_split_ratio = 1.0,
        split_bias = 0,
    },
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})
