-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Просмотр медиа телеграм

hl.window_rule({
    name  = "float_on",
    match = {
        class = "org.telegram.desktop",
        title = "Media viewer",
    },
    float = true,
})

hl.window_rule({
    name  = "size_70__70_",
    match = {
        class = "org.telegram.desktop",
        title = "Media viewer",
    },
    size = "70% 70%",
})

hl.window_rule({
    name  = "center_on",
    match = {
        class = "org.telegram.desktop",
        title = "Media viewer",
    },
    center = true,
})

-- General file chooser rules

hl.window_rule({
    name  = "float_on",
    match = {
        class = "xdg-desktop-portal-gtk",
    },
    float = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        class = "xdg-desktop-portal-gtk",
    },
    center = true,
})

hl.window_rule({
    name  = "size__monitor_w_0_5_",
    match = {
        class = "xdg-desktop-portal-gtk",
    },
    size = "(monitor_w*0.5) (monitor_h*0.5)",
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "File Upload|Open|Save|Select|Library",
    },
    float = true,
})

hl.window_rule({
    name  = "center_on",
    match = {
        title = "File Upload|Open|Save|Select|Library",
    },
    center = true,
})

hl.window_rule({
    name  = "size__monitor_w_0_5_",
    match = {
        title = "File Upload|Open|Save|Select|Library",
    },
    size = "(monitor_w*0.5) (monitor_h*0.5)",
})

-- YouTube/mpv

hl.window_rule({
    name  = "float_on",
    match = {
        class = "mpv",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        title = "Picture-in-Picture",
    },
    float = true,
})

hl.window_rule({
    name  = "stay_focused_on",
    match = {
        class = "mpv",
    },
    stay_focused = true,
})

-- Блютуз

hl.window_rule({
    name  = "float_on",
    match = {
        class = "kitty",
        title = "bluetooth-manager",
    },
    float = true,
})

hl.window_rule({
    name  = "size_70__70_",
    match = {
        class = "kitty",
        title = "bluetooth-manager",
    },
    size = "70% 70%",
})

hl.window_rule({
    name  = "center_on",
    match = {
        class = "kitty",
        title = "bluetooth-manager",
    },
    center = true,
})

-- Календарь

hl.window_rule({
    name  = "float_on",
    match = {
        class = "kitty",
        title = "calendar",
    },
    float = true,
})

hl.window_rule({
    name  = "size_70__70_",
    match = {
        class = "kitty",
        title = "calendar",
    },
    size = "70% 70%",
})

hl.window_rule({
    name  = "center_on",
    match = {
        class = "kitty",
        title = "calendar",
    },
    center = true,
})

-- Диспетчер задач

hl.window_rule({
    name  = "float_on",
    match = {
        class = "kitty",
        title = "task-monitor",
    },
    float = true,
})

hl.window_rule({
    name  = "size_70__70_",
    match = {
        class = "kitty",
        title = "task-monitor",
    },
    size = "70% 70%",
})

hl.window_rule({
    name  = "center_on",
    match = {
        class = "kitty",
        title = "task-monitor",
    },
    center = true,
})

-- Календарь (duplicate)

hl.window_rule({
    name  = "float_on",
    match = {
        class = "kitty",
        title = "calendar",
    },
    float = true,
})

hl.window_rule({
    name  = "size_70__70_",
    match = {
        class = "kitty",
        title = "calendar",
    },
    size = "70% 70%",
})

hl.window_rule({
    name  = "center_on",
    match = {
        class = "kitty",
        title = "calendar",
    },
    center = true,
})

-- Аудио микшер

hl.window_rule({
    name  = "float_on",
    match = {
        class = "kitty",
        title = "audio-mixer",
    },
    float = true,
})

hl.window_rule({
    name  = "size_70__70_",
    match = {
        class = "kitty",
        title = "audio-mixer",
    },
    size = "70% 70%",
})

hl.window_rule({
    name  = "center_on",
    match = {
        class = "kitty",
        title = "audio-mixer",
    },
    center = true,
})

-- Файловый менеджер Yazi

hl.window_rule({
    name  = "float_on",
    match = {
        title = "Yazi",
    },
    float = true,
})

hl.window_rule({
    name  = "size_70__70_",
    match = {
        title = "Yazi",
    },
    size = "70% 70%",
})

hl.window_rule({
    name  = "center_on",
    match = {
        title = "Yazi",
    },
    center = true,
})

hl.layer_rule({
    match = {
        namespace = "swaync-control-center",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "swaync-notification-window",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "swaync-control-center",
    },
    ignore_alpha = 0,
})

hl.layer_rule({
    match = {
        namespace = "swaync-notification-window",
    },
    ignore_alpha = 0,
})

hl.layer_rule({
    match = {
        namespace = "swaync-control-center",
    },
    ignore_alpha = 0.5,
})

hl.layer_rule({
    match = {
        namespace = "swaync-notification-window",
    },
    ignore_alpha = 0.5,
})

hl.layer_rule({
    match = {
        namespace = "hyprpicker",
    },
    no_anim = true,
})

hl.layer_rule({
    match = {
        namespace = "selection",
    },
    no_anim = true,
})
