-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.workspace_rule({
    workspace = 1,
})

hl.workspace_rule({
    workspace = 2,
})

hl.workspace_rule({
    workspace = 3,
})

hl.workspace_rule({
    workspace = 4,
})

hl.workspace_rule({
    workspace = 5,
})

hl.workspace_rule({
    workspace = 6,
})

hl.workspace_rule({
    workspace = 7,
})

hl.workspace_rule({
    workspace = 8,
})

hl.workspace_rule({
    workspace = 9,
})

hl.workspace_rule({
    workspace = 10,
})
