$text = rgb(ffffff)
$textAlpha = ffffff

$subtext1 = rgb(aaaaaa)
$subtext1Alpha = aaaaaa

$subtext0 = rgb(888888)
$subtext0Alpha = 888888

$overlay2 = rgb(666666)
$overlay2Alpha = 666666

$overlay1 = rgb(444444)
$overlay1Alpha = 444444

$overlay0 = rgb(333333)
$overlay0Alpha = 333333

$surface2 = rgb(262626)
$surface2Alpha = 262626

$surface1 = rgb(1a1a1a)
$surface1Alpha = 1a1a1a

$surface0 = rgb(111111)
$surface0Alpha = 111111

$base = rgb(000000)
$baseAlpha = 000000

$mantle = rgb(000000)
$mantleAlpha = 000000

$crust = rgb(000000)
$crustAlpha = 000000

$border-primary = rgb(ffffff)
